### ISSUE TITLE
Non chef managed Splunk Server(Indexer)

### ISSUE THREAD

**Issue by tzvikaz** [chef-cookbooks/chef-splunk#27] opened 2015-01-01 22:40 UTC
More of a question.
splunk_servers is populated through search

```ruby
splunk_servers = search( # ~FC003
  :node,
  "splunk_is_server:true AND chef_environment:#{node.chef_environment}"
).sort! do
  |a, b| a.name <=> b.name
end
```

What happens when there is no such node, when the indexer is not part of chef infra?

**Comment by leftathome** [comment] 2015-03-04 19:11
An empty search will yield an empty set, so the `@splunk_servers` template variable will be empty.

This means `#each` won't enumerate through anything, so that section of the template will not be rendered.

Which means the Splunk agent will be configured without that set of outputs.

(That's best-case - depending on how a search is written it can also result in uncaught exceptions failing a Chef run, but I don't think this one will barf in that way...)

The good news is that this is just node data, so you could gin up a fake node entry for the not-managed-by-Chef Splunk Enterprise server and that would probably make the recipe happy.

Another option would be to add some logic to the client recipe:
````
  if search_results.length < 1
    search_results = [ some attributes picked up elsewhere in the cookbook ]
  end
````

**Comment by danieljimenez** [comment] 2015-09-12 23:20
+1

**Comment by tas50** [comment] 2016-08-05 22:37
This is a dupe of #15

**Closed by tas50** 2016-08-05 22:37 UTC
